### ISSUE TITLE
can't deepcopy JsonDicts (and other containers)

### ISSUE THREAD

**Issue by czue** [dimagi/jsonobject#115]
not sure if this is an issue or expected behavior

```
>>> from jsonobject import *
>>> import copy
>>> class Obj(JsonObject):
...   foo = DictProperty()
... 
>>> obj = Obj(foo={"some": "value"})
>>> copy.deepcopy(obj.foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 230, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 237, in _deepcopy_tuple
    y.append(deepcopy(a, memo))
  File "/usr/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object
```

**Comment by dannyroberts** [comment]
@esoergel looks like this was introduced between jsonobject 0.4 and 0.6 according to https://github.com/dimagi/commcare-hq/pull/4647#issuecomment-60982452. If this is fixed within a week, is that fast enough?

**Comment by dannyroberts** [comment]
Also according to https://github.com/dimagi/commcare-hq/commit/ff67f36b7cfc7169b639922bf8a5735444cf31ad#commitcomment-10420066, `copy.deepcopy(obj)` works just fine, but `copy.deepcopy(obj.foo)` fails

**Comment by esoergel** [comment]
@dannyroberts I need to do a bit more digging to figure the rest of the issue out, but I'm hoping to be able to circumvent the issue altogether, in which case the timing is less critical.

**Comment by trentgerman** [comment]
Any progress on this one?

**Comment by dannyroberts** [comment]
Looks from the conversation history that we dropped it without a timeline to complete. As a workaround, `Obj.wrap(obj.to_json())` is conceptually equivalent, although I realize you may not have access to the code that makes the call to deepcopy.
