### ISSUE TITLE
BUG: Pip install fails

### ISSUE THREAD

**Issue by israel-fl** [dimagi/jsonobject#146]
Unable to install jsonobject for python 3.6

Calling:

`pip install jsonobject`

inside a virtual environment fails with:

```
Collecting jsonobject==0.9.2
  Using cached https://files.pythonhosted.org/packages/5a/cc/ad69cdbddd69b2f2c0f8e124ca3f1341590d875872d3314a6f9868a67c8f/jsonobject-0.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-filj8r41/jsonobject/setup.py", line 8, in <module>
        import six
    ModuleNotFoundError: No module named 'six'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-filj8r41/jsonobject/
```

This is the first time I encounter this issue. Obviously, installing the `six` module prior to this works, however this is an issue in an automated environment when installing from the requirements.txt file.

**Comment by emord** [comment]
@nickpell I think this was introduced in https://github.com/dimagi/jsonobject/commit/f10e8db6d901b2bad2f62354b0d9f2a2a2a0b2b2#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by dannyroberts** [comment]
To elaborate (and I've run into this before), running `setup.py` cannot require importing `six`, because even though the package declares `six` as a dependency, `setup.py` needs to get run before pip picks up the dependency and installs it.

**Comment by nickpell** [comment]
I see.  Fixing now.

**Comment by nickpell** [comment]
Fix here: https://github.com/dimagi/jsonobject/pull/147

**Comment by israel-fl** [comment]
@nickpell Thanks for the quick response and resolution.
